### ISSUE TITLE
Add "powered by ODK" to footer

### ISSUE THREAD

**Issue by lognaturel** [getodk/web-forms#105]
Should be small and tasteful, link to website.

**Comment by alyblenkin** [comment]
Here are a [few ideas](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5504-113083&t=2f5dfhcmoToEtifN-1)! I'm leaning towards 1 and 2, but curious to know what you all think.

**Comment by sadiqkhoja** [comment]
Are we thinking to make it a license requirement for clients/host applications not to hide it?

**Comment by lognaturel** [comment]
I don't think so. I don't think it's actually a valid/enforceable addition to Apache 2.0. My feeling is that host applications run by folks who understand that it's helpful to the long-term viability of a component they're relying on would tend to leave it regardless and folks who don't know/care would remove it no matter what.
