### ISSUE TITLE
Adjust UI for mobile and tablet

### ISSUE THREAD

**Issue by sadiqkhoja** [getodk/web-forms#128]
Walk few steps towards making the web-forms responsive to different screen sizes, specifically for mobiles and tablets:

- Remove question card
- Make the questions container full width
- Move Form title in the row of print and language controls
- Show hamburger icon on mobile screens

[Figma](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=4952%3A19348&t=7iwnrIOJ3ZZvV7MW-1)
<img width="946" alt="Screenshot 2024-06-20 at 12 17 13 PM" src="https://github.com/getodk/web-forms/assets/7871340/a3d56380-8a8e-4263-a27f-dae0f1700c33">

**Design tweaks:**
- Title should be smaller on mobile (I think we may need to tweak the font sizes in general so it feels responsive. It might be too small on desktop right now)
- [Dialog ](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5328%3A118478&t=stYrE0uZdWmXMJLz-1)for changing the language on mobile could wider so it doesn't feel so squished, and we can remove the 'X' because we have cancel at the bottom. Rounded edges might also make it more consistent with the tablet/desktop experience. 
-  Sent button needs more spacing on the right

**Comment by alyblenkin** [comment]
Looking good! I think we can add more spacing between the radio button and text. As well as more spacing within the "Save" button so it's wider and easier to tap on mobile. 

![Image](https://github.com/getodk/web-forms/assets/7871340/aaa41995-8089-4922-8a75-dde87647a125)

I'm going to add a placeholder issue for adjusting the font size and spacing. I think we will need to play around with this after we implementing the outlines to the options.
