### ISSUE TITLE
Design tweaks

### ISSUE THREAD

**Issue by alyblenkin** [getodk/web-forms#139]
Starting a list of small changes to improve the over all experience

**Spacing, weights, text fields**
- [x] Vertical spacing after text boxes (can we leverage the vue components here)
- [x] Make the spacing between selects consistent with the text fields (selects seems more spaced apart) 
- [x] Reduce text size/weight of title
- [x] Text field needs to be a lighter grey because it looks disabled (try #F7F8F9)
- [x] Hover state for text fields can be lighter 
- [x] For displayed values and conditionally disabled fields, it's hard to tell it's updating because the text is too light - Needs design (~~Idea: when it's dynamic maybe add a light blue highlight animation~~)

**Icons**
- [x] More consistent alignment of controls (icons in larger views, hamburger menu in smaller). Vertical centering makes those a moving target. 
- [x] more menu still appears pretty small 
- [x] Chevrons for groups are not aligned in the middle with the text

**Elevation**
- [x] [Remove boarder and elevation](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5258-108702&t=7E9o9DdPAwWqHTRs-1) so it's flat
- [x] Flat buttons

**Repeats**
- [x] Add a "+" icon to the [add button for repeats with label](https://www.figma.com/design/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?node-id=5023-34916&t=V2GBznX4TxQWpKlP-1). 
- [x] Adding the repeat label (really the label of the outer group) in the button text. That would be similar to Collect (see comment below)
- [x] The number should match the label text weight

**Comment by lognaturel** [comment]
For the add button for repeats, what do you think about also adding the repeat label (really the label of the outer group) in the button text? That would be similar to Collect. For example, if the repeat label is "person", the button label would be "Add person". The danger is that of course the repeat label could be poorly selected. In Collect, the repeat name is used as-is and put in quotes (Add "person"?). We could consider doing things like forcing lowercase.

**Comment by alyblenkin** [comment]
@lognaturel Yes, I think this would be a super nice improvement and would align nicely with Collect!

**Comment by sadiqkhoja** [comment]
Comments by @eyelidlessness about Form Header on #132:

> I was curious to see how wrapping looks for forms with long titles. Pretty good! I think we may want to iterate later on... 
> - More consistent alignment of controls (icons in larger views, hamburger menu in smaller). The vertical centering makes those a moving target. I think we'll probably want some design guidance on that.
> - Maybe slightly reducing text size/weight over a certain character length? (Honestly the weight feels pretty heavy regardless of length, wrapping.)

**Comment by lognaturel** [comment]
Normalize vertical spacing, especially after text boxes:
<img width="450" alt="Screenshot 2024-06-28 at 4 02 49 PM" src="https://github.com/getodk/web-forms/assets/967540/2c76decc-06b7-4e50-a9d3-d16f77c9a523">
