### ISSUE TITLE
Show read-only input without a value without a control or space for a value

### ISSUE THREAD

**Issue by lognaturel** [getodk/web-forms#21]
As a form designer
I want to write some text without a value
So that I can provide information or guidance to form users

This is the `note` type in XLSForm. If there is no value, there should be no control or vertical space for a value.

Typically a `note` in XLSForm only has a label. But because XLSForm makes `note` an alias to type `string` with the `readonly` bind attribute set to `true()`, everything that's allowed for a `string` is allowed for a `note`. [Form showing what could be done with the XLSForm `note` type](https://docs.google.com/spreadsheets/d/12EQhUKACxbBs4OLs8pIkFkywFO0oNjmxw7S7ZIAWHQI/edit?gid=1068911091#gid=1068911091).

**Comment by sadiqkhoja** [comment]
done in #181
