### ISSUE TITLE
Make version information accessible to make troubleshooting easier

### ISSUE THREAD

**Issue by lognaturel** [getodk/web-forms#217]
As a user (system administrator, data collector, etc)
  I want to include version information when reporting an issue
  So that the development team can fix it

ODK tools typically provide version information from `git describe --tags --dirty --always`. This information is available from different places:
- At the bottom of the landing screen in Collect. This is so data collectors can quickly verify that they're on the expected version while training, etc
- From the help menu in Central
- From a system summary screen and at the bottom of the offline menu in Enketo

Some ideas for Web Forms:
- tooltip when hovering over "powered by"
- bottom of the screen

**Comment by alyblenkin** [comment]
I think bottom of the page works well! We could display it under the "powered by ODK" label so the user can see it if they are  desktop or on their phone. [Figma link](https://www.figma.com/design/6v0NnvayfDlaQhYpjv37Bn/Web-Forms?node-id=234-5069&t=FX1DIthW728DuhfP-1)
