### ISSUE TITLE
Add thumbnail for Web Forms Preview page

### ISSUE THREAD

**Issue by alyblenkin** [getodk/web-forms#238]
The default ODK image shows up in the thumbnail when I share a link to the preview page. 

We want people to see a screenshot of the Web Forms Preview instead. 
https://getodk.org/web-forms-preview/

![Web Froms Preview 1 (1)](https://github.com/user-attachments/assets/9a45e476-107a-4d78-98db-a77bdf0b0ace)

**Comment by alyblenkin** [comment]
@yanokwa do we still need this?

**Comment by yanokwa** [comment]
I think it'd be nice to have for when we share the link directly. It's not something I can easily do though.

**Comment by lognaturel** [comment]
@yanokwa This seems like it belongs in the website HEAD, not here?

**Comment by yanokwa** [comment]
Ugh, you are right. Fixed at https://github.com/getodk/website/pull/654
