### ISSUE TITLE
Make Central show a form preview using web forms

### ISSUE THREAD

**Issue by lognaturel** [getodk/web-forms#24]
Blocked by #20
Blocked by #29

E.g if the preview button is alt-clicked

* Like the current Enketo-based preview, it's opened in a full screen view.
  * So it's easy to share with mobile users, etc 
* ~Use the same EnketoID to build a link. Maybe instead of /-/preview/enketoID we use /wf/preview/enketoID and make that public so it can be tried on a range of devices (especially mobile)~ This feels like it was an accidental feature
* Clicking/tapping the send button shows a validation summary and reminder it's a preview only

**Comment by sadiqkhoja** [comment]
@lognaturel I guess we can close this

**Comment by lognaturel** [comment]
🎉🎉🎉
